### ISSUE TITLE
`Oracles` Service/Controller 

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#144]
#### What would you like to be added:

After the completion of https://github.com/DeFiCh/jellyfish/issues/202 `rpc_oracles.cpp` we need OraclesController to be implemented on the whale side which is sanitized for modern development.

Very similar to Token & PoolPair Controller. You can expect to implement the controller in the same design pattern as the existing controllers. Your end consumer is the explorer and light wallet to display price in a graph.

/triage accepted
/assign @jingyi2811 
/priority important-soon

/area module-api

**Comment by jingyi2811** [comment]
Start doing today

**Comment by jingyi2811** [comment]
Product Design

There are 4 price feed categories

- Crypto (For eg: BTC/USD, ETH/USD)
- Stock (For eg: APPL/USD, TSLA/USD)
- Commodity (For eg: OIL/USD, GOLD/USD)
- Forex (For eg: EUR/USD, SGD/USD)

On the landing page, the system should display all the active price feed cards in pagination. Users can narrow down the selection result by checking any of these 4

- Category
- Status [All, Active (By default), Inactive]
- Token
- Currency

checkboxes or key in the token/currency value directly in the textbox and click the search button. Then, users can only select 1 price feed card at a time.

Every card has 2 view types

- Lite (Display the current price info)
- Detail (Display all the historical price info)

Lite view

- Token/Currency
- Current price
- Last 24-hour price percentage difference
- Active/Inactive (Inactive = There is no price offered for the past 15 minutes)
- Category
- Oracle info

    1. How many Oracle responded and contributed to creating the price? What are their names? And when they responded?
    2. What was the last price updated time?
    3. What was the price of every Oracle?

Detail view
- A chart that shows the historical price (24 H, 7 D, 30 D, 90 D, 3M, 6M, 1Y, 5Y, ALL)

Bonus
- Can we allow users to log in and update their preferred currency and price list? So the system can display their preferred data first on the list.
- We probably need to build a few APIs to allow developers to query the historical price.
- We can have some kind of portfolio management, which allows the users to key in and save the token amount they hold, and the system can calculate their total token worth base on current prices.

**LSM Database**

We need 2 keys

- Oracle {oracleid}-{token}-{currency}-{blockheight} : {price}-{weightage}-{timestamp}
- PriceFeed {token}-{currency}-{blockheight} : {price}-{timestamp}

We only allow GET and PUT operations on both keys. There is no DELETE. If a price feed or oracle was removed from the blockchain, we still keep them in the LSM database

**Indexing**

Interception should happen on setOracleData on every block

We need to get the data similar to

Calling listLatestRawPrice RPC and put In Oracle key
Calling listPrice RPC and put in PriceFeed key
