### ISSUE TITLE
Add account system balances to `module.indexer`

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/whale#153]
#### What would you like to be added:

Index account system balances (i.e. token balances) as we may need to perform complex calculations and queries on sets of data e.g. calculate rich list.

#### Why is this needed:

We may need to perform complex calculations and queries on sets of data e.g. calculate rich list.

**Comment by fuxingloh** [comment]
I was thinking about this the other day, it's kinda impossible to properly implement real-time balances. We need to calculate reward at every block that will carry forward the problems of non lazy implementation where we need to loop through all account.

**Comment by fuxingloh** [comment]
We can implement some sort of bucketed updating where x number of addresses are updated at every block to prevent intensive computing at each block connect. Or have a separate runner/worker to do rich list updating.

> blocks https://github.com/DeFiCh/whale/issues/34

**Comment by ivan-zynesis** [comment]
Most likely require wallet mechanics (multiple address) to complete the account balance aggregation.

**Comment by ivan-zynesis** [comment]
Another huge challenge will be rewards which require full data of masternodes, LM token of single wallet vs full ecosystem, this will/has to be the very last piece of the puzzle.

**Comment by canonbrother** [comment]
> We can implement some sort of bucketed updating where x number of addresses are updated at every block to prevent intensive computing at each block connect. Or have a separate runner/worker to do rich list updating.

`some sort of bucketed` sounds like `shards` in blockchain
