### ISSUE TITLE
`URLSearchParams` is not supported on mobile apps

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/whale#155]
#### What happened:
In `whale.api.client`, it is using `URLSearchParams` for parsing of URL parameters https://github.com/DeFiCh/whale/blob/fa7e64d66907c7b188f4ea44f6c8cd4f4fcc775c/packages/whale-api-client/src/whale.api.client.ts#L83. When using it on mobile devices (Android - React Native), it doesn't support `URLSearchParams`. It causes API requests to fail. 
#### What you expected to happen:
API request should work normally regardless of client.
#### How to reproduce it (as minimally and precisely as possible):
1. Call any API from `whale.api.client`
2. Will get error on the request

![image (1)](https://user-images.githubusercontent.com/25013382/122361389-c7884d80-cf89-11eb-9bdf-0390a43a9232.png)

**Comment by fuxingloh** [comment]
Implemented in #154 but we need a closer look in the future, might need to refactor.

/area whale-api-client
