### ISSUE TITLE
`MasternodeController`

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#189]
#### What would you like to be added:

After the completion of https://github.com/DeFiCh/jellyfish/issues/48 `rpc_masternode.cpp` we need MasternodeController to be implemented on the whale side which is sanitized for modern development.

Similar to existing Token & PoolPair Controller. You can expect to implement the controller in the same design pattern as the existing controllers. Your end consumer is the explorer for the purpose of displaying Masternode information.

/assign @siradji you need to write the specification and design it for explorer use-cases. Take the customer-obsessed stance and write your product release notes before you do the development. This allows you to understand what it's is for and the direction you are developing it for. @siradji will also be doing the implementation on UI Explorer after it's designed.

You can keep the development narrative in this issue, and post it here directly.

/triage accepted
/priority important-soon
/area module-api

**Comment by siradji** [comment]
## Overview

The masternode API provides information on masternodes for consumers. 

## Product design

- On the masternode page, a user would be able to view list of all masternodes with pagination option.
- A user can click on a masternode to get information about that masternode the block count of that masternode.
- On the masternode page, a user would be able to view the count of active masternodes
- On the masternode page, a user would be able to filter and narrow down the masternode list
    - Masternode state (eg Enabled, Resigned and Banned)
    - Owner address (filter and show masternodes of a provided owner address )

### Core functionality of the Masternode API:

- List of all masternodes
- Information about a masternode
- Blocks count of a masternode
- Active masternode count

## Possible features that can be implemented

With authentication implemented, a user can resign a masternode they own.

**Comment by fuxingloh** [comment]
> ## Product design
> * On the masternode page, a user would be able to filter and narrow down the masternode list
>   * Masternode state (eg Enabled, Resigned and Banned)
>   * Owner address (filter and show masternodes of a provided owner address )

Are these features provided from ain via the existing RPCs? 

If not, we need to index the data in `module.indexer`, might be out of scope for this issue. You should create a separate PR for this.

> ## Possible features that can be implemented
> ~~With authentication implemented, a user can resign a masternode they own.~~

not doing authentication, they can self sign and resign on their own (wallet feature)

**Comment by fuxingloh** [comment]
Follow REST convention to the dot, query string should only be used for pagination (filter via path). There is plenty of narratives written in the project. You can refer to them.

> FYI read this: https://github.com/DeFiCh/whale/pull/35

**Comment by siradji** [comment]
> If not, we need to index the data in `module.indexer`, might be out of scope for this issue. You should create a separate PR for this.

@fuxingloh, the filtering will be implemented on the front end that is how i planned, but i do not know if indexing the data will be better.

**Comment by fuxingloh** [comment]
> > If not, we need to index the data in `module.indexer`, might be out of scope for this issue. You should create a separate PR for this.
> 
> @fuxingloh, the filtering will be implemented on the front end that is how i planned, but i do not know if indexing the data will be better.

Does the existing RPC in `jellyfish` that you have implemented the interfaces for support filtering?

**Comment by siradji** [comment]
> > > If not, we need to index the data in `module.indexer`, might be out of scope for this issue. You should create a separate PR for this.
> > 
> > 
> > @fuxingloh, the filtering will be implemented on the front end that is how i planned, but i do not know if indexing the data will be better.
> 
> Does the existing RPC in `jellyfish` that you have implemented the interfaces for support filtering?

@fuxingloh , Yes it supports filtering. I checked the indexer and i don't think we need it for the filtering.

**Comment by siradji** [comment]
I will start working on the Controller now.
