### ISSUE TITLE
Add RPCs and endpoints to support existing stats API

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/whale#222]
#### What would you like to be added:

Some of these are already being worked on/implemented, keeping a list here for reference.

Endpoints:

- [ ] Endpoint to get total liquidity in USD for a poolpair
- [ ] Endpoint to get the yearly pool reward in DFI for a poolpair
- [ ] Endpoint to get the APY for a poolpair
- [ ] Endpoint to get 24h volume for a poolpair
- [ ] Endpoint to get the total supply of DFI token
- [ ] Endpoint to get the total supply of DFI token in all poolpairs
- [ ] Endpoint to get a token rich list
- [ ] Endpoint to get swap transactions over a range of start - end blocks

RPCs:

Some of the below may be replaced by existing endpoints rather than calling RPCs directly (Most likely the block related calls)

- [x] `getburninfo`
- [ ] `getTxOutsetInfo`
- [x] `listcommunitybalances`
- [x] `listtokens`
- [x] `gettoken`
- [ ] `validateaddress` (Maybe can use local implementation)
- [x] `getblockcount` (I think already have this or can use existing `getblockchaininfo`)
- [x] `getpoolpair`
- [x] `getgov`
- [x] `getaccount`
- [x] `listpoolpairs`
- [x] `getblock`
- [x] `getblockhash`
- [x] `getcustomtx`
- [ ] `listanchors`

**Comment by fuxingloh** [comment]
Implemented on Jellyfish under `apps/legacy-api`
