### ISSUE TITLE
Add endpoint to check if address is valid

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/whale#245]
#### What would you like to be added:
Endpoint to validate if address is a valid defi address. 
#### Why is this needed:
For form validations, like when sending tokens etc.

**Comment by thedoublejay** [comment]
@fuxingloh is it a valid request? Feel free to close if it's already existing

**Comment by fuxingloh** [comment]
It's a package in jellyfish https://github.com/DeFiCh/jellyfish/tree/main/packages/jellyfish-address
