### ISSUE TITLE
Endpoint - `/stats/supply`

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#310]
#### What would you like to be added:

Provide additional statistical data in `/stats` endpoint.

```json
{
  "supply": {
    "circulating": number,
    "burned": number,
    "total": number,
    "max": 1200000000
  }
}
```

- `supply.max` = 1,200,000,000
- `supply.burned` = Fee/Emission/Address Burns (basically all the burn from getBurnInfo)
- `supply.total` = Total Minted at block height
- `supply.circulating` = `supply.total` - `supply.burned`

https://academy.binance.com/en/glossary/circulating-supply

/triage accepted
/area module-api
/priority important-soon

**Comment by fuxingloh** [comment]
/assign @siradji 

Do ping @monstrobishi for more details

**Comment by siradji** [comment]
@monstrobishi, need your guide on this too. thanks

**Comment by monstrobishi** [comment]
Assuming this is UTXO DFI, looking at the existing stats api it pulls it from the Bitcore node, indicating some indexing is required. To get an accurate value you might need to sum up all of the UTXO in the indexer, but I think Fuxing is suggesting here to calculate the emission up to the max years, and work backwards based on the block height.

I.e. "Total is 1.2 billion (based on whitepaper), every block produces ~190 blocks * the block height (that's circulating)"

For total you will want to read the section on the white paper on supply: https://defichain.com/white-paper/#token-issuance-schedule-via-staking

**Comment by fuxingloh** [comment]
@siradji what happen to the PR for this?

**Comment by joeldavidw** [comment]
@fuxingloh @siradji I will work on this

**Comment by fuxingloh** [comment]
@ivan-zynesis I need your help with this, wanted to tackle this myself but this is much more complicated than I thought due to the evolution of rewards.

Initially, I did a deterministic calculation but it proves to be complex due to various historical evolution of rewards minting. Post Eunos hard fork, the reward distribution stabilized into a deterministic subsidy calculation.

My suggestion is we take a snapshot of up till let's say Fort Canning or Eunos HardFork. (By looping through all addresses that exist within DFC till a height.) And we derive a deterministic calculation from there onwards?

**Comment by fuxingloh** [comment]
With https://github.com/DeFiCh/jellyfish/pull/1037 merged, we can use `BlockSubsidy` utility to get the running supply of DFI.
