### ISSUE TITLE
Masternode Stats Aggregation Indexing

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#325]
#### What would you like to be added:

Indexing total masternode stats, for `/stats` endpoint.

```ts
interface MasternodeStats {
  total: number
  tvl: number
  locked: [
    {weeks: 0, tvl: }
    {weeks: 260, tvl: }
    {weeks: 520, tvl: }
  ]
}
```

/triage accepted
/assign @monstrobishi 
/area module-indexer module-model

**Comment by monstrobishi** [comment]
Can you clarify what `normal` means in this context

Note for `total` and the rest, the number will represent MN in the `ENABLED` state only (will exclude other states such as `PRE_RESIGNED`)
