### ISSUE TITLE
More clear error when using whale client pointing at an undeployed whale version

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/whale#336]
#### What happened:

At the moment when you use client 0.7.0 and there is no 0.7.0 deployed, the resulting error message is `undefined - undefined`.

#### What you expected to happen:

It would make sense to have a slightly more useful error in this case e.g. `Server unreachable`, etc.

#### How to reproduce it (as minimally and precisely as possible):

Point client at non existent url

**Comment by fuxingloh** [comment]
Seems like I need to do something on the Ocean deployment.

**Comment by fuxingloh** [comment]
Have been implemented on ocean deployment:

> https://ocean.defichain.com/v0.99/mainnet/stats

```json
{
  "error": {
    "code":404,
    "message":"Unable to handle the request, do you have the correct endpoint? E.g. https://ocean.defichain.com/{version}/{network}/...",
    "type":"NotFound"
  }
}
```
