### ISSUE TITLE
Indexing: `PoolPair` with DfTx Indexer

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#369]
#### What would you like to be added:

Similar to https://github.com/DeFiCh/whale/pull/215 but rewrite to use `DfTxIndexer` to index PoolPair for querying. Replication of `DeFiCh/ain` poolpair API with the additional APR. This means the indexer needs to track all swaps, add/remove to/from the pool pair.

In addition to PoolPair indexing.

We need to index:
- PoolPairSwap
- PoolPairSwapInterval (similar to #283)
- PoolPairGate (can't think of a better name to describe Enter/Exit, PoolPairIO, PoolPairEntry?)

**Comment by monstrobishi** [comment]
Will assume Rewards are outside of the scope of this ticket, should come in another ticket/PR

**Comment by ivan-zynesis** [comment]
Do we need `inteval` here? Unlike oracle, external tickers are not paced by block, pool pair price by block sounds okay to me.
Naming wise, 🤔 just go simple low level, maybe `PoolPairReserve`

**Comment by fuxingloh** [comment]
Done, the rest will be moved to jellyfish, @eli-lim is working on it
