### ISSUE TITLE
block.controller.ts

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#4]
#### What would you like to be added:

Block Controller for blocks.

`id` can be block hash or block height.

```
GET v1/:network/blocks
GET v1/:network/blocks/:id
GET v1/:network/blocks/:id/transactions
GET v1/:network/blocks/:id/transactions/:txId
GET v1/:network/blocks/:id/transactions/:txId/vins
GET v1/:network/blocks/:id/transactions/:txId/vouts
```

**Comment by fuxingloh** [comment]
Using data from `module.indexer`

**Comment by fuxingloh** [comment]
@aikchun to prevent you from working blind, you should write the specification and design it for explorer use-cases. 

Take the customer-obsessed stance and write your product release notes (API notes) before you do the development. This allows you to understand what it's is for and the direction you are developing it for. You will also be doing the implementation on UI Explorer after it's designed.

This is inline with:
1. https://github.com/DeFiCh/whale/issues/144
2. https://github.com/DeFiCh/whale/issues/189

**Comment by aikchun** [comment]
# Overview

We want to provide more API to the upcoming explorer, namely:
1. Getting the latest block of the block chain
2. Getting a specific block.
3. Getting the transactions that were signed in a specific the block.

# Context

## Why

The [current explorer](https://explorer.defichain.com/#/DFI/mainnet/home) has limited features and functionalities. As we want to provide users with more tools on the explorer, `Whale`, as the super index, would be required to have the endpoints and methods to handle the requests.

# Solution

## Get the latest block
`GET - v0/:network/block/tip` to fetch the block data of the latest block in the blockchain.
`GET - v0/:network/block:id` to fetch a particular block data in the blockchain by providing the `id`/`hash` in the URL.
`GET - v0:/:network/block/:id/transactions` would fetch a list of transactions of a block, referenced by the `id`/`hash` in the URL.

**Comment by fuxingloh** [comment]
> ~~1. Getting the latest block of the block chain~~
Getting a list of blocks, sorted in descending order from the tip.

**Comment by fuxingloh** [comment]
`:id` -> HASH `[0-f]{64}` or height `[0-9]{1,}`

GET - v0/:network/blocks
GET - v0/:network/blocks/:id
GET - v0/:network/blocks/:id/transactions

**Comment by fuxingloh** [comment]
2 additional endpoint that is required

```
GET v1/:network/blocks/:id/transactions/:txId/vin
GET v1/:network/blocks/:id/transactions/:txId/vouts
```

**Comment by aikchun** [comment]
> 2 additional endpoint that is required
> 
> ```
> GET v1/:network/blocks/:id/transactions/:txId/vin
> GET v1/:network/blocks/:id/transactions/:txId/vouts
> ```

May I suggest these endpoints be part of a separate issue/pull request to keep the PR small?

**Comment by fuxingloh** [comment]
Sure!

**Comment by aikchun** [comment]
Reopened issue as these two endpoints have not been resolved.
```
GET v1/:network/blocks/:id/transactions/:txId/vin
GET v1/:network/blocks/:id/transactions/:txId/vouts
```
