### ISSUE TITLE
Decentralized Loan Endpoints

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#405]
#### What would you like to be added:

Provide an endpoint to get decentralized loan information for Light Wallet.

1. Loan
2. Auction
3. Vault
4. Loan Tokens
5. Collateral Tokens
6. Loan Schemes

```
GET v0/:network/loan/?
```

/triage accepted
/area module-api
/priority important-soon

**Comment by jingyi2811** [comment]
**Loan endpoints**

This is the recommendation of how the loan endpoints should be and we will expose the endpoints from whale to the light wallet. 


**1) Scheme**

listLoanScheme 
- id
- minColRatio
- InterestRate

getLoanScheme (SchemeName)

- id
- minColRatio
- InterestRate


**2) CollateralToken**

listCollateralTokens

- Token
- Factor
- Interest

getCollateralToken(token)

- Factor
- Interest

**3) LoanToken**

listLoanTokens
- Token
- Interest

getLoanTokens(token)

- Interest

**4) Vault**

listVaults
- loanSchemeId
- ownerAddress
- isUnderLiquidation
- Batches
    - Index
    - Collaterals
    - loan
- collateralAmount
- loanAmount
- collateralValue
- loanValue
- currentRatio

getVault(loanSchemeId)
- ownerAddress
- isUnderLiquidation
- Batches
    - Index
    - Collaterals
    - loan
- collateralAmount
- loanAmount
- collateralValue
- loanValue
- currentRatio

**Comment by jingyi2811** [comment]
**1) Scheme**

/loan/schemes

listLoanSchemes 
- id
- minColRatio
- InterestRate

/loan/scheme/:id

getLoanScheme (id)

- minColRatio
- InterestRate

[Note: I remove default from the return value. Don't think it is important]

**Comment by jingyi2811** [comment]
**2) CollateralToken**

/loan/collateral/tokens

listCollateralTokens

- Token
- Factor
- Interest

/loan/collateral/token/:id

getCollateralToken(token)

- Factor
- Interest

[Note: I remove activateAfterBlock from the return value. We should only consider those activated collateral tokens, not those which not yet activated]

**Comment by jingyi2811** [comment]
**3) LoanToken**

/loan/tokens

listLoanTokens
- Token
- Interest

/loan/token/:id

getLoanToken(token)
- Interest

[Note: I remove priceFeedId from the return value. The reason is all the priceFeedIds MUST be USD]

**Comment by jingyi2811** [comment]
**4) Vault**

/loan/vaults

listVaults
- loanSchemeId
- ownerAddress
- isUnderLiquidation
- Batches
    - Index
    - Collaterals
    - loan
- collateralAmount
- loanAmount
- collateralValue
- loanValue
- currentRatio

/loan/vault/:id

getVault(loanSchemeId)
- ownerAddress
- isUnderLiquidation
- Batches
    - Index
    - Collaterals
    - loan
- collateralAmount
- loanAmount
- collateralValue
- loanValue
- currentRatio

[Note: 

1. If liquidation was triggered: collateralAmount, loanAmount, collateralVault, loanValue and currentRatio would not have value. If liquidation was not triggered,  batches would not have value.  

2. currentRatio = collateralValue / loanValue * 100 ]

**Comment by jingyi2811** [comment]
**6) Loan info** 
Provide a holistic view on loan statistics

/loan/info

getLoanInfo
* collateralValueUSD
* loanValueUSD

[Note: I remove collateralTokens, loanTokens, loanSchemes from the return value because the value is exists in #1, #2, #3]

**Comment by jingyi2811** [comment]
7) Take loan

/loan/take/:vaultid/:amount

takeLoan(vaultId, amount)
* txId

**Comment by jingyi2811** [comment]
**9) Auction bid**

/auction/bid/:vaultId/:index/:address/:amount

auctionBid(vaultId, index, ownerAddress, amount)

- txId

[Note: amount is in amount@token format (For eg: 10@DBTC ]

**Comment by jingyi2811** [comment]
Total endpoints = 16

/loan/schemes
/loan/scheme/:id
/loan/collateral/tokens
/loan/collateral/token/:id
/loan/tokens
/loan/token/:id
/vaults/:size/:next
/vault/:id
/vault/create/:address/:schemeid
/vault/update/:vaultid/:address/:schemeid
/vault/deposit/:vaultid/:address/:amount
/loan/interest
/loan/info
/loan/take/:vaultid/:address/:amount
/loan/payback/:vaultid/:address/amount
/auction/bid/:vaultId/:index/:address/:amount

**Comment by thedoublejay** [comment]
@fuxingloh @jingyi2811 I have some suggestions for items 1,2,3:
Would it be better to have a single endpoint for it? From the UI side, we don't need to have a dedicated API for schemes, scheme detail etc since user cannot edit/update it on the light wallet. Can we just have one API call, let's say /loan/tokens/ with all required details by combining all results from other APIs?:
`GET /loan/tokens` 
1. tokenDetails (Name, symbol etc.), loanScheme (id, minColRatio etc.), collateralToken

**Comment by fuxingloh** [comment]
> @fuxingloh @jingyi2811 I have some suggestions for items 1,2,3:
> Would it be better to have a single endpoint for it? From the UI side, we don't need to have a dedicated API for schemes, scheme detail etc since user cannot edit/update it on the light wallet. Can we just have one API call, let's say /loan/tokens/ with all required details by combining all results from other APIs?:
> `GET /loan/tokens`
> 
> 1. tokenDetails (Name, symbol etc.), loanScheme (id, minColRatio etc.), collateralToken

Give me a moment for this, I will be collating the final version for this.

**Comment by jingyi2811** [comment]
> @fuxingloh @jingyi2811 I have some suggestions for items 1,2,3:
> Would it be better to have a single endpoint for it? From the UI side, we don't need to have a dedicated API for schemes, scheme detail etc since user cannot edit/update it on the light wallet. Can we just have one API call, let's say /loan/tokens/ with all required details by combining all results from other APIs?:
> `GET /loan/tokens`
> 
> 1. tokenDetails (Name, symbol etc.), loanScheme (id, minColRatio etc.), collateralToken

You can get the same result from getLoanInfo RPC call

https://github.com/DeFiCh/whale/issues/405#issuecomment-928674794

**Comment by fuxingloh** [comment]
Many thanks @jingyi2811, I will break this issue into smaller issues
