### ISSUE TITLE
refactor `module.indexer`

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#50]
#### What would you like to be added:

Refactor `module.indexer` code to be cleaner. The current implementation is done in a jiffy which is necessitated for speed. We would need to refactor `module.indexer` with a cleaner design for better evolution of the code. Might be worth while to implement CQRS design pattern for indexing.

- [ ] Automated Invalidating via Prune, Undo, Redo e.t.c
- [ ] Separation of DfTx for transport and storage.
- [ ] DfTx Abstraction

**Comment by fuxingloh** [comment]
`module.indexer` should also be refactored into an isolated single purpose module/package where all it does is indexing.

**Comment by monstrobishi** [comment]
@fuxingloh Are indexers by design append-only? Should we enforce that as a rule? It would make automated invalidation much simpler

**Comment by fuxingloh** [comment]
> @fuxingloh Are indexers by design append-only? Should we enforce that as a rule? It would make automated invalidation much simpler

Initially thinking it from a graph theory perspective, it makes sense but the more complex implementation e.g. `aggregation` pattern doesn't really follow the traditional ledger approach as it's aggregating latest balances when there is balance/movement activity

**Comment by fuxingloh** [comment]
Unassigned as it will be moved to `DeFiCh/jellyfish` in Q4.
