### ISSUE TITLE
`DeFiCh/ain:2.0.x` Loan Indexing and API

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/whale#541]
#### Loan Scheme
- [ ] setLoanScheme @canonbrother  #560 
- [ ] setDefaultLoanScheme @canonbrother #622 
- [ ] destroyLoanScheme @canonbrother #612

#### Collateral/Loan Token
- [ ] setCollateralToken @ivan-zynesis 
- [ ] setLoanToken @monstrobishi #588 
- [ ] setLoanToken (keep loan token history) @ivan-zynesis 
- [ ] updateLoanToken @ivan-zynesis 

#### Vault
- [ ] createVault @monstrobishi 
- [ ] updateVault @monstrobishi 
- [ ] depositToVault @canonbrother 
- [ ] takeLoan
- [ ] loanPayback @monstrobishi 
- [ ] withdrawFromVault 
- [ ] closeVault
- [ ] placeAuctionBid @canonbrother 

### API
- [ ] listLoanSchemes @canonbrother #627 
- [ ] getLoanScheme @canonbrother #627 
- [ ] listCollateralTokens
- [ ] getCollateralToken
- [ ] getInterest
- [ ] getLoanToken
- [ ] listLoanTokens
- [ ] getLoanInfo
- [ ] listAuctions @jingyi2811 
- [ ] listAuctionHistory @jingyi2811

**Comment by fuxingloh** [comment]
Not all API/Indexing are important, to focus on `VaultHistory` first.

**Comment by monstrobishi** [comment]
I'll take over some of the vault tasks
