### ISSUE TITLE
Change poolpair token symbol trimming between 8/16 chars based on FC height

### ISSUE THREAD

**Issue by ivan-zynesis** [DeFiCh/whale#567]
#### What would you like to be added:
Remove token symbol trimming to 8 characters long in token/poolpair indexers.

#### Why is this needed:
To have consistent behavior is post FC defid.
https://github.com/DeFiCh/ain/compare/v1.8.4...v2.0.0#diff-5b5f5b126aad5172f5e15066f2926f4afb57e75eb624b509f56233c14cd4b5c9R1040-R1042

**Comment by monstrobishi** [comment]
I can't find any evidence this was changed in /ain, can you link the relevant PR or commit with the lines highlighted? Max symbol length for tokens is still 8 on master

**Comment by ivan-zynesis** [comment]
> I can't find any evidence this was changed in /ain, can you link the relevant PR or commit with the lines highlighted? Max symbol length for tokens is still 8 on master

Linked ain diff in description

**Comment by monstrobishi** [comment]
Adding a note here that we need to do a height check for FC height and then use 8/16 characters based on the height
