### ISSUE TITLE
`defichain-dependencies` to auto update all with scope to the latest next version

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#61]
#### What would you like to be added:

When the next version of `@defichain/*` is available, we should update it automatically via the workflow
https://github.com/DeFiCh/whale/blob/main/.github/workflows/defichain-dependencies.yml

We also need a cleaner way to manage `@latest` and `@next` deps update and syncing.

#### Why is this needed:

This will ensure we are always at the tip of the latest dependency.

**Comment by 777Michaeld777** [comment]
When I select "create a new wallet" for DeFiChain  it gives me a pass phrase and no option for a "SEED" to set up the wallet. Can anyone help me?
