### ISSUE TITLE
remove of Indexer that aren't exposed

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#686]
#### What would you like to be added:

Reduce the scope of Indexer implementation by removing indexers that aren't used or exposed as an endpoint.

#### Why is this needed:

As part of the https://github.com/DeFiCh/jellyfish/issues/580 consolidation effort, we want to make it saner to migrate to jellyfish. At the same time keeping this project saner for long-term maintainability. This project will also eventually be consolidated into `DeFiCh/jellyfish/apps/whale-api` for legacy reasons limiting the scope will allow us to move at greater convenience.

/area module-indexer
/assign @ivan-zynesis 
/triage accepted

**Comment by ivan-zynesis** [comment]
@fuxingloh I ran through all indexer, non of them can be dropped. There are only 2 indexers (write into mapper) which are not directly exposed through API, `Loan Token` and `Pool Pair`. However, both of them are affecting the `tokenId` counter, any removal will screw up the `tokenMapper`

**Comment by fuxingloh** [comment]
I believe we are not exposing TokenMapper anywhere?

**Comment by ivan-zynesis** [comment]
> I believe we are not exposing TokenMapper anywhere?

Oh yeah, didn't notice this like most fundamental table is actually unused, the API is using RPC. Will continue this.
