### ISSUE TITLE
mempool.controller.ts

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/whale#7]
#### What would you like to be added:

Get a transaction from mempool with given txid.

```
GET v1/:network/mempool/transactions/:txid
```

**Comment by fuxingloh** [comment]
deprioritized for now

**Comment by siradji** [comment]
@fuxingloh , just for clarification, is this ticket referring to `getRawMempool` and `getMempoolInfo` in `blockChain` RPC?

**Comment by fuxingloh** [comment]
> @fuxingloh , just for clarification, is this ticket referring to `getRawMempool` and `getMempoolInfo` in `blockChain` RPC?

This ticket refers to showing active `transactions` in mempool that aren't confirmed yet.

**Comment by siradji** [comment]
@fuxingloh , as `mempool` RPC does not have a query  limit by default, i am trying to use `SliceResponse` #35 , but i guess it is deprecated in favour of `ApiPagedResponse`. Am i correct?

**Comment by fuxingloh** [comment]
> @fuxingloh , as `mempool` RPC does not have a query limit by default, i am trying to use `SliceResponse` #35 , but i guess it is deprecated in favour of `ApiPagedResponse`. Am i correct?

This is awkward, which means we have to index the data in whale as it's not supposed on `DeFiCh/ain`.
/needs triage let's put this on hold now

**Comment by siradji** [comment]
@fuxingloh , is this still open?
