### ISSUE TITLE
API Temporarily Unavailable

### ISSUE THREAD

**Issue by 0ptim** [DeFiCh/whale#727]
Wanted to check out the ocean API but getting `503 Service Temporarily Unavailable` when calling `https://ocean.defichain.com/`.

I don't know if this is planned or not.

Cheers! 😃

**Comment by Stonygan** [comment]
I think you must use a correct Entrypoint: e.g. https://ocean.defichain.com/v0/mainnet/stats

**Comment by 0ptim** [comment]
Thanks, @Stonygan! Dumb me… Used `https://ocean.defichain.com/v0/mainnet` and expected this to return something.
