### ISSUE TITLE
prefix on cache keys

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/whale#82]
#### What would you like to be added:
Enumeration to construct a prefix on cache key

#### Why is this needed:
Safety wise, its better to prefix the cache key `eg: token_${key}, poolpair_${key}` which provides a scope protection that helps preventing key overwritten

**Comment by fuxingloh** [comment]
/assign @fuxingloh 
/priority urgent-now

I will work on this now, should be a quick one

**Comment by fuxingloh** [comment]
Wrote the specification without testing in https://github.com/DeFiCh/whale/tree/fuxingloh/cache

/assign @canonbrother can you help take over this, I am a little too occupied now.
