### ISSUE TITLE
Add caching to token of TokenController

### ISSUE THREAD

**Issue by jingyi2811** [DeFiCh/whale#85]
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Add caching to token of TokenController

#### Which issue(s) does this PR fixes?:

Fixes https://github.com/DeFiCh/whale/pull/30#discussion_r635039352

**Comment by fuxingloh** [comment]
Wait for https://github.com/DeFiCh/whale/issues/82 to closed before working on this.

/area module-api
/triage accepted

**Comment by fuxingloh** [comment]
Unassigned @jingyi2811 for you to focus on Oracles
